Update to new accounts api
owncloud/ocis-migration pull request #7
Opened 2020-05-20 16:36 UTC by butonic

2020-05-20 18:33 UTC, refs requested changes

2020-05-20 18:33 UTC, refs commented on pkg/command/import.go
>  			ss := accounts.NewAccountsService("com.owncloud.accounts", grpc.NewClient())
`com.owncloud.accounts` => `com.owncloud.api.accounts` ([see](https://github.com/owncloud/ocis-accounts/pull/30/files#diff-94a57a917fa4cb2936d50745c2c79517R49))

2020-05-22 06:10 UTC, refs commented
depends on https://github.com/owncloud/ocis-accounts/pull/30

2020-06-22 08:14 UTC, butonic commented
replaced by https://github.com/owncloud/ocis-migration/pull/8

2020-06-22 08:14 UTC, closed without merging